version: "3"

services:

  zookeeper:
    image: oddpoet/zookeeper
    hostname: zookeeper
    command:
      - "2181"
    ports:
      - "2181:2181"
    networks:
      cu_imgsearch_net:
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      cu_imgsearch_net:
#  kafka_manager:
#    image: sheepkiller/kafka-manager
#    environment:
#      ZK_HOSTS: "zookeeper:2181"
#      KM_CONFIGFILE: "/opt/application.conf"
#    volumes:
#      - ../../conf/km.conf:/opt/application.conf
#    depends_on:
#      - zookeeper
#      - kafka
#    networks:
#      cu_imgsearch_net:
  hbase:
    image: kevinsvds/hbase
    hostname: hbase
    ports:
      - "9090:9090"
      - "9095:9095"
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    networks:
      cu_imgsearch_net:
  pusher:
    image: svebork/columbia_image_search:1.0
    hostname: cuimg_push
    stdin_open: true
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - $repo_path:$indocker_repo_path
    #command: $docker_push_cmd
    command: "bash ${indocker_repo_path}/scripts/run_local_images_pusher.sh -c ${conf_name} -r ${indocker_repo_path}"
    links:
      - kafka
    depends_on:
      - kafka
    networks:
      cu_imgsearch_net:
  processor:
    image: svebork/columbia_image_search:1.0
    hostname: cuimg_proc
    stdin_open: true
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - $repo_path:$indocker_repo_path
    #command: $docker_proc_cmd
    command: "bash ${indocker_repo_path}/scripts/run_processing.sh -c ${conf_name} -r ${indocker_repo_path}"
    links:
      - kafka
      - hbase
    depends_on:
      - kafka
      - hbase
    networks:
      cu_imgsearch_net:
  search:
    image: svebork/columbia_image_search:1.0
    hostname: cuimg_search
    stdin_open: true
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - $repo_path:$indocker_repo_path
    ports:
      - $port_host:5000
    #command: $docker_search_cmd
    command: "bash ${indocker_repo_path}/scripts/run_search.sh -c ${conf_name} -r ${indocker_repo_path} -e ${endpoint}"
    links:
      - hbase
    depends_on:
      - hbase
    networks:
      cu_imgsearch_net:

networks:
  cu_imgsearch_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16

volumes:
  cuimgsearch-resources-volume: