zookeeper:
  image: oddpoet/zookeeper
  hostname: zookeeper
  command:
    - "2181"
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka
  hostname: kafka
  stdin_open: true
  tty: true
  command:
    - "bash"
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_PORT: 9092
hbase:
   image: kevinsvds/hbase
   hostname: hbase
   ports:
     - "9090:9090"
     - "9095:9095"
     - "60000:60000"
     - "60010:60010"
     - "60020:60020"
     - "60030:60030"
   links:
     - zookeeper
