version: "3"

services:

  img_processor:
    image: svebork/columbia_image_search:1.0
    hostname: ${extr_conf_name}
    stdin_open: true
    tty: true
    cap_add:
      - IPC_LOCK
    environment:
      # General environment variables
      - input_type
      - verbose
      - "conf_name=${extr_conf_name}"
      - "extr_type=${extr_type}"
      - "extr_nb_threads=${extr_nb_threads}"
      # Kafka related environment variables
      - images_topic
      - kafka_servers
      - kafka_security
      - "extr_check_consumer_group=${extr_check_consumer_group}"
      - "extr_proc_consumer_group=${extr_proc_consumer_group}"
      - "updates_topic=${updates_topic}"
      # Hbase related environment variables
      - hbase_host
      - "table_sha1infos=${table_sha1infos}"
      - "table_updateinfos=${table_updateinfos}"
      - "batch_update_size=${batch_update_size}"
    # nothing really needs to be persistent here. no other volumes needed
    volumes:
      - $repo_path:$indocker_repo_path
    command: ["bash", "-c", "mkdir ${indocker_repo_path}/conf/generated/ || true && python ${indocker_repo_path}/setup/ConfGenerator/create_conf_extractor.py -o ${indocker_repo_path}/conf/generated/ && bash ${indocker_repo_path}/scripts/run_processing.sh -c ${extr_conf_name} -r ${indocker_repo_path}"]
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "7"
